name: Publish to Github

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    env:
      RELEASE_FILE_NAME: /tmp/synced_collections.tar.gz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create release assets
        run: |
          tar -czf ${{ env.RELEASE_FILE_NAME }} .
      - name: Generate Changelog
        run: |
          python << EOF > ${GITHUB_WORKSPACE}/generated_changelog.txt
          import re

          include  = False
          lines = []

          with open("${GITHUB_WORKSPACE}/changelog.txt") as f:
              for line in f:
                  if re.search("\[\d+\.\d+\.\d+\] -- \d{4}-\d{2}-\d{2}", line):
                      if include:
                          # We're now encountering the second time, so break
                          break
                      else:
                          # First header, start including lines
                          include = True
                          lines.append(line)
                  elif include:
                      lines.append(line)

          print(''.join(lines))
          EOF

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.RELEASE_FILE_NAME }}
          body_path: ${GITHUB_WORKSPACE}/generated_changelog.txt
