name: Publish to GitHub

on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    env:
      GENERATED_CHANGELOG: /tmp/generated_changelog.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Changelog
        run: |
          python .github/workflows/generate-changelog.py > ${{ env.GENERATED_CHANGELOG }}
      - name: Compute Tag
        run: |
          RELEASE_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "RELEASE_TAG=${RELEASE_TAG}" >> "$GITHUB_ENV"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ env.GENERATED_CHANGELOG }}
          tag_name: ${{ env.RELEASE_TAG }}
