name: Run Unit Tests

on:
  # trigger on pull requests
  pull_request:

  # trigger on all commits to main
  push:
    branches:
      - 'main'

  # trigger on request
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-26]
        python: [3.14]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Python environment
      uses: glotzerlab/workflows/setup-uv@204dc7c0f82720090703712694b7cab761aacaa0 # 0.13.0
      with:
        lockfile: "requirements/requirements-test.txt"
    - name: Install the package
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pytest -rs tests/ -v
