name: Run Unit Tests

on:
  # trigger on pull requests
  pull_request:

  # trigger on all commits to main
  push:
    branches:
      - 'main'

  # trigger on request
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-26]
        python: [3.14]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: ${{ matrix.python }}
    - name: Set up Python environment
      uses: glotzerlab/workflows/setup-uv@00c67cb577c36bdc2570845fc62d1a30e3383012 # 0.14.0
      with:
        lockfile: "requirements/requirements-test.txt"
    - name: Install the package
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pytest -rs tests/ -v
